language: python
dist: xenial
python:
  - 3.5
  - 3.8
branches:
  only:
    - master
env:
  global:
    - secure: X8Aqo9EwwOF5MJ3P9XDpZvFq2djvo6afB1EzJV9p10DxhrPXPAz3vO1UCdBhHbd2RohGQRulaqATzWd4ICo3woLmxTxl96180sgUBRbYY3vNM7z1wb3VO+YSxfLbTw0MkBwXcZv1/JQIhhmrnTkfmyX89ks0fWGti6ORSxdKs+Y=
    - secure: ceiuLB8lLidI+3Ohk/SiO48StGEgxbDDLto6PHdz8rFW6S4VISQF4PqB3X8jGEkyiiSO+sBdm9OYmgHy7zPdJTw/DYQT+2xN2EGx2vrn2NtoBPkCwu/2wCVQ5z0gzqzzncgfnt3lk9CX/mhVoRbGYpt130CgiaVvP9us5+2KAfI=
services:
  - docker
cache:
  - pip
install:
  - pip install -r requirements/ci.txt
# command to run tests
script:
  - pycodestyle
  - pylint regression/
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker --version;
    sudo apt-get -y update;
    sudo apt-get -y install -o Dpkg::Options::="--force-confnew" docker-ce=18.03.0~ce-0~ubuntu;
    docker --version;
    docker-compose build;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASS";
    docker push edxops/e2e:latest;
    fi
