# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # We initially use the base Ubuntu 12.04 box to bootstrap the image
  #config.vm.box     = "precise64"
  #config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # We then upload the box to S3 to speed up future installations
  config.vm.box     = "edx-e2e-ubuntu"
  config.vm.box_url = "https://s3.amazonaws.com/vagrant.testeng.edx.org/edx-e2e-ubuntu.box"

  config.vm.network :private_network, ip: "192.168.111.222"

  config.vm.synced_folder "..", "/opt/dev/edx-e2e-tests"

  config.vm.provider :virtualbox do |vb|
     vb.gui = true
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbooks/vagrant-e2e.yml"
    ansible.inventory_path = "inventory.ini"
    ansible.verbose = "vvv"
    ansible.host_key_checking = false
  end

end
