#!/usr/bin/env bash

# Set environment variables that Jenkins would set
# This is useful for running tests locally using SauceLabs
#
# You will need to start Sauce Connect locally
# on port 4445.  Use this command after sourcing this script:
#
#   java -jar /usr/local/bin/Sauce-Connect.jar $SAUCE_USER_NAME $SAUCE_API_KEY -P $SELENIUM_PORT

# See https://saucelabs.com/docs/platforms/webdriver for available browsers
export SELENIUM_BROWSER="firefox"
export SELENIUM_VERSION="25"
export SELENIUM_PLATFORM="Windows 8"
export SELENIUM_HOST="localhost"
export SELENIUM_PORT=4445

# See https://saucelabs.com/docs/connect for instructions
export SAUCE_USER_NAME="{{ sauce_user_name }}"
export SAUCE_API_KEY="{{ sauce_api_key }}"
