name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  run_quality:
    name: quality checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.5','3.8']

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Quality checks
      run: |
        pycodestyle
        pylint regression/
