# For non-draft changes to named release branches:
# - Check if the user is a maintainer (listed in the MERGERS env var in the
#     .github/workflows/pr-automerge-open-release.yml workflow).
# - If so, approve the pull request.
#   - Merge the PR when the author comments `@openedx-community-bot merge`.
#
# Required organization secrets
# - CC_GITHUB_TOKEN or GITHUB_TOKEN

name: Automerge BTR open-release PRs

on:
  issue_comment:
    branches:
      - open-release/*
    types:
      - created
      - edited
  pull_request_target:
    branches:
      - open-release/*
    types:
      - opened
      - edited
      - ready_for_review

jobs:
  automerge:
    uses: openedx/.github/.github/workflows/pr-automerge-open-release.yml@master
